# -*- coding: utf-8 -*-
"""Proyecto 3 Deep Learning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ymwDz7zkGh9HpIr0zhK_91mbSg0BJroN

**Sección** 1 — Setup e instalación
"""

# ============================================================
# SECCIÓN 1 — SETUP E INSTALACIÓN
# ============================================================
!pip install -q transformers>=4.41.0
!pip install -q datasets
!pip install -q shap
!pip install -q lime
!pip install -q gradio
!pip install -q scikit-learn matplotlib seaborn

print("✅ Librerías instaladas correctamente")

import torch
import random
import numpy as np

# Verificar GPU (Muy importante para Transformers)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"🖥️ Dispositivo: {device}")
if device.type == "cuda":
    print(f"   GPU: {torch.cuda.get_device_name(0)}")
else:
    print("⚠️ No hay GPU disponible. Ve a: Entorno de ejecución → Cambiar tipo de entorno → T4 GPU")

# Fijar semillas para que siempre nos dé el mismo resultado en las sustentaciones
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

print(f"\n🌱 Semillas fijadas (SEED={SEED})")

"""Sección 2 — Carga del dataset y EDA"""

# ============================================================
# SECCIÓN 2 — CARGA DEL DATASET Y EDA
# ============================================================
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

# Cargar el dataset de SMS Spam (archivo tabulado)
url = "https://raw.githubusercontent.com/justmarkham/pycon-2016-tutorial/master/data/sms.tsv"
df = pd.read_csv(url, sep='\t', header=None, names=['label', 'text'])

# Convertimos 'ham' a 0 y 'spam' a 1
df['label_num'] = df['label'].map({'ham': 0, 'spam': 1})

print(f"Total de mensajes: {len(df)}")
print(f"\nDistribución de clases:")
print(df['label'].value_counts())

# Gráfico sencillo del desbalance
plt.figure(figsize=(6, 4))
sns.countplot(data=df, x='label', palette=['#4CAF50', '#F44336'])
plt.title('Desbalance de Clases: Ham vs Spam')
plt.show()

# ============================================================
# Preprocesamiento de texto tradicional
# ============================================================
import re

def limpiar_texto(texto):
    texto = str(texto).lower() # Todo a minúsculas
    texto = re.sub(r'http\S+|www\S+', 'URL', texto) # Cambiamos links por la palabra URL
    texto = re.sub(r'\d+', 'NUMERO', texto) # Cambiamos números por la palabra NUMERO
    texto = re.sub(r'[^\w\s]', ' ', texto) # Quitamos puntuación rara
    texto = re.sub(r'\s+', ' ', texto).strip() # Quitamos espacios extra
    return texto

df['text_clean'] = df['text'].apply(limpiar_texto)

# División de datos: 70% Train, 15% Validacion, 15% Test
X = df['text_clean'].values
y = df['label_num'].values

X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.30, random_state=SEED, stratify=y)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.50, random_state=SEED, stratify=y_temp)

print(f"\nTamaño Entrenamiento: {len(X_train)}")
print(f"Tamaño Validación: {len(X_val)}")
print(f"Tamaño Prueba (Test): {len(X_test)}")

# Calculamos los pesos para que la red le preste más atención al Spam
from sklearn.utils.class_weight import compute_class_weight
pesos = compute_class_weight('balanced', classes=np.array([0,1]), y=y_train)
pesos_tensor = torch.tensor(pesos, dtype=torch.float).to(device)
print(f"\nPesos de clase calculados -> Ham: {pesos[0]:.3f} | Spam: {pesos[1]:.3f}")

"""Sección 3 — Baseline: BiLSTM

Vocabulario y Dataset:
"""

# ============================================================
# SECCIÓN 3 — BASELINE: BiLSTM con Word Embeddings
# ============================================================
from torch.utils.data import Dataset, DataLoader
from torch.nn.utils.rnn import pad_sequence
import torch.nn as nn

# 1. Creamos un diccionario manual de palabras (estilo estudiante)
word2idx = {'<PAD>': 0, '<UNK>': 1}
idx2word = {0: '<PAD>', 1: '<UNK>'}
idx = 2

for oracion in X_train:
    for palabra in oracion.split():
        if palabra not in word2idx:
            word2idx[palabra] = idx
            idx2word[idx] = palabra
            idx += 1

print(f"Palabras únicas en vocabulario: {len(word2idx)}")

# Función para convertir oraciones a números
def codificar_texto(texto, max_len=128):
    tokens = [word2idx.get(w, 1) for w in texto.split()] # 1 es <UNK> si no la conoce
    return tokens[:max_len]

# 2. Dataset de PyTorch
class SMSDataset(Dataset):
    def __init__(self, texts, labels):
        self.data = []
        for text, label in zip(texts, labels):
            tokens = codificar_texto(text)
            self.data.append((torch.tensor(tokens, dtype=torch.long),
                              torch.tensor(label, dtype=torch.long)))

    def __len__(self):
        return len(self.data)

    def __getitem__(self, index):
        return self.data[index]

def pad_collate(batch):
    texts, labels = zip(*batch)
    texts_padded = pad_sequence(texts, batch_first=True, padding_value=0)
    return texts_padded, torch.stack(labels)

train_loader = DataLoader(SMSDataset(X_train, y_train), batch_size=32, shuffle=True, collate_fn=pad_collate)
val_loader   = DataLoader(SMSDataset(X_val, y_val), batch_size=32, shuffle=False, collate_fn=pad_collate)
test_loader  = DataLoader(SMSDataset(X_test, y_test), batch_size=32, shuffle=False, collate_fn=pad_collate)

# 3. Definición de la Red BiLSTM
class MiBiLSTM(nn.Module):
    def __init__(self, vocab_size, embed_dim=64, hidden_dim=64):
        super(MiBiLSTM, self).__init__()
        self.embedding = nn.Embedding(vocab_size, embed_dim, padding_idx=0)
        # Bidirectional = True es lo que hace que lea de izquierda a derecha y viceversa
        self.lstm = nn.LSTM(embed_dim, hidden_dim, batch_first=True, bidirectional=True)
        self.dropout = nn.Dropout(0.3)
        self.fc = nn.Linear(hidden_dim * 2, 2) # *2 porque es bidireccional (ida y vuelta)

    def forward(self, x):
        emb = self.embedding(x)
        out, (hidden, cell) = self.lstm(emb)
        # Tomamos el último estado oculto de ambas direcciones
        hidden_concatenado = torch.cat((hidden[-2,:,:], hidden[-1,:,:]), dim=1)
        hidden_drop = self.dropout(hidden_concatenado)
        return self.fc(hidden_drop)

modelo_lstm = MiBiLSTM(len(word2idx)).to(device)
criterio = nn.CrossEntropyLoss(weight=pesos_tensor) # Usamos los pesos por el desbalance
optimizador = torch.optim.Adam(modelo_lstm.parameters(), lr=0.001)

import time

# 4. Bucle de Entrenamiento (Restaurado a 10 épocas)
EPOCHS = 10
print("\nIniciando entrenamiento del BiLSTM...")
start_time = time.time()

for epoch in range(EPOCHS):
    # Fase de Entrenamiento
    modelo_lstm.train()
    train_loss = 0.0
    for textos, etiquetas in train_loader:
        textos, etiquetas = textos.to(device), etiquetas.to(device)

        optimizador.zero_grad()
        predicciones = modelo_lstm(textos)
        loss = criterio(predicciones, etiquetas)
        loss.backward()
        optimizador.step()

        train_loss += loss.item()

    # Fase de Validación
    modelo_lstm.eval()
    val_loss = 0.0
    correctos = 0
    total = 0
    with torch.no_grad():
        for textos, etiquetas in val_loader:
            textos, etiquetas = textos.to(device), etiquetas.to(device)
            predicciones = modelo_lstm(textos)
            loss = criterio(predicciones, etiquetas)
            val_loss += loss.item()

            _, clase_predicha = torch.max(predicciones, 1)
            correctos += (clase_predicha == etiquetas).sum().item()
            total += etiquetas.size(0)

    print(f"Época {epoch+1:02d}/{EPOCHS} | Train Loss: {train_loss/len(train_loader):.4f} | Val Loss: {val_loss/len(val_loader):.4f} | Val Acc: {correctos/total:.4f}")

tiempo_total = time.time() - start_time
print(f"\n[*] Entrenamiento BiLSTM completado en {tiempo_total//60:.0f}m {tiempo_total%60:.0f}s")

"""DistilBERT Fine-Tuning

Dataset y tokenizador:
"""

# ============================================================
# SECCIÓN 4 — MODELO AVANZADO: DistilBERT (Transformers)
# ============================================================
from transformers import DistilBertTokenizerFast, DistilBertForSequenceClassification
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay

# Descargamos el modelo base de HuggingFace
tokenizer = DistilBertTokenizerFast.from_pretrained('distilbert-base-uncased')
modelo_bert = DistilBertForSequenceClassification.from_pretrained('distilbert-base-uncased', num_labels=2).to(device)

# Dataset especial para BERT (Él hace su propia tokenización)
class DatasetBERT(Dataset):
    def __init__(self, textos, etiquetas):
        self.encodings = tokenizer(list(textos), truncation=True, padding=True, max_length=128, return_tensors='pt')
        self.labels = torch.tensor(etiquetas, dtype=torch.long)

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        item = {key: val[idx] for key, val in self.encodings.items()}
        item['labels'] = self.labels[idx]
        return item

train_loader_bert = DataLoader(DatasetBERT(X_train, y_train), batch_size=16, shuffle=True)
val_loader_bert   = DataLoader(DatasetBERT(X_val, y_val), batch_size=16, shuffle=False)
test_loader_bert  = DataLoader(DatasetBERT(X_test, y_test), batch_size=16, shuffle=False)

optimizador_bert = torch.optim.AdamW(modelo_bert.parameters(), lr=2e-5)

import time

# Bucle de Entrenamiento BERT (Restaurado a 5 épocas)
EPOCHS_BERT = 5
print("\nIniciando Fine-Tuning de DistilBERT...")
start_time = time.time()

for epoch in range(EPOCHS_BERT):
    # ENTRENAMIENTO
    modelo_bert.train()
    train_loss = 0.0
    for batch in train_loader_bert:
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['labels'].to(device)

        optimizador_bert.zero_grad()
        outputs = modelo_bert(input_ids, attention_mask=attention_mask, labels=labels)

        loss = outputs.loss
        loss.backward()
        optimizador_bert.step()
        train_loss += loss.item()

    # VALIDACIÓN
    modelo_bert.eval()
    val_loss = 0.0
    with torch.no_grad():
        for batch in val_loader_bert:
            input_ids = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)
            labels = batch['labels'].to(device)

            outputs = modelo_bert(input_ids, attention_mask=attention_mask, labels=labels)
            val_loss += outputs.loss.item()

    print(f"Época {epoch+1:02d}/{EPOCHS_BERT} | Train Loss: {train_loss/len(train_loader_bert):.4f} | Val Loss: {val_loss/len(val_loader_bert):.4f}")

tiempo_total_bert = time.time() - start_time
print(f"\n[*] Fine-Tuning DistilBERT completado en {tiempo_total_bert//60:.0f}m {tiempo_total_bert%60:.0f}s")

# Evaluación Final en el Test Set
modelo_bert.eval()
predicciones_finales = []
etiquetas_reales = []

with torch.no_grad():
    for batch in test_loader_bert:
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['labels']

        outputs = modelo_bert(input_ids, attention_mask=attention_mask)
        _, preds = torch.max(outputs.logits, 1)

        predicciones_finales.extend(preds.cpu().numpy())
        etiquetas_reales.extend(labels.numpy())

print("\n" + "="*50)
print("REPORTE DE DISTILBERT EN TEST SET")
print("="*50)
print(classification_report(etiquetas_reales, predicciones_finales, target_names=['Ham', 'Spam']))

# Dibujar matriz
ConfusionMatrixDisplay.from_predictions(etiquetas_reales, predicciones_finales, display_labels=['Ham', 'Spam'], cmap='Blues')
plt.title("Matriz de Confusión - DistilBERT")
plt.show()

"""s5 analisis errores"""

# ============================================================
# SECCIÓN 5 — ANÁLISIS DE ERRORES (LA CAJA DE CRISTAL)
# ============================================================


print("🔍 ANALIZANDO DÓNDE SE EQUIVOCÓ EL MODELO...\n")

falsos_positivos = [] # Era Normal, el modelo dijo Spam
falsos_negativos = [] # Era Spam, el modelo dijo Normal

for texto, real, pred in zip(X_test, etiquetas_reales, predicciones_finales):
    if real == 0 and pred == 1:
        falsos_positivos.append(texto)
    elif real == 1 and pred == 0:
        falsos_negativos.append(texto)

print("❌ FALSOS POSITIVOS (Mensajes normales bloqueados por error):")
for i, msg in enumerate(falsos_positivos[:3]):
    print(f"  {i+1}. {msg}")

print("\n⚠️ FALSOS NEGATIVOS (Spam peligroso que el modelo dejó pasar):")
for i, msg in enumerate(falsos_negativos[:3]):
    print(f"  {i+1}. {msg}")

print("\n💡 Conclusión para la sustentación:")
print("Aunque las métricas son altísimas, el lenguaje humano es ambiguo. Entrenar por más épocas")
print("solo causaría Overfitting. La solución es aplicar IA Explicable (XAI).")

"""XAI"""



# ============================================================
# SECCIÓN 6 — XAI (LIME) Y DEMO EN GRADIO
# ============================================================
from lime.lime_text import LimeTextExplainer
import gradio as gr
import torch

# Guardamos el modelo para usarlo en LIME
modelo_bert.save_pretrained('mi_modelo_spam')
tokenizer.save_pretrained('mi_modelo_spam')

def predecir_probabilidades(textos):
    textos_limpios = [limpiar_texto(t) for t in textos]

    encodings = tokenizer(textos_limpios, truncation=True, padding=True, max_length=128, return_tensors='pt').to(device)
    with torch.no_grad():
        outputs = modelo_bert(**encodings)
    probabilidades = torch.softmax(outputs.logits, dim=1).cpu().numpy()
    return probabilidades

# ¡AQUÍ ESTABA EL ERROR! Faltaba inicializar el explicador de LIME
explicador = LimeTextExplainer(class_names=['Normal (Ham)', 'Fraude (Spam)'])

# Diccionario sencillo para explicarle al usuario
palabras_peligrosas = ['urgent', 'free', 'win', 'prize', 'click', 'account', 'cash', 'text', 'call', 'reply']

def analizar_mensaje_xai(mensaje):
    if not mensaje.strip():
        return "Escribe un mensaje por favor.", ""

    probabilidades = predecir_probabilidades([mensaje])[0]
    es_spam = probabilidades[1] > 0.5

    # LIME saca las palabras más importantes
    explicacion = explicador.explain_instance(mensaje, predecir_probabilidades, num_features=5, labels=[1])
    palabras_top = [word for word, weight in explicacion.as_list(label=1) if weight > 0]

    # Armar la respuesta reactiva
    if es_spam:
        estado = f"🚨 ALERTA: SPAM DETECTADO (Confianza: {probabilidades[1]*100:.1f}%)"

        # Cruzar con nuestro diccionario
        tacticas_usadas = [p for p in palabras_top if p.lower() in palabras_peligrosas]

        if tacticas_usadas:
            razon = f"El modelo bloqueó este mensaje porque usa tácticas comunes de estafa.\nPalabras clave detectadas que activaron la alarma: {tacticas_usadas}"
        else:
            razon = f"El modelo detectó una estructura inusual sospechosa.\nPalabras que más influyeron en la decisión: {palabras_top}"
    else:
        estado = f"✅ MENSAJE SEGURO (Confianza: {probabilidades[0]*100:.1f}%)"
        razon = "El mensaje sigue patrones de conversación normal. No se detectaron intenciones maliciosas."

    return estado, razon

# Interfaz visual
demo = gr.Interface(
    fn=analizar_mensaje_xai,
    inputs=gr.Textbox(lines=3, placeholder="Pega el SMS aquí...", label="Mensaje a analizar"),
    outputs=[gr.Textbox(label="Diagnóstico"), gr.Textbox(label="Explicación de la IA (XAI)")],
    title="🛡️ Filtro de Smishing con IA Explicable",
    description="Universidad Militar Nueva Granada - Proyecto Deep Learning",
    examples=[
        ["URGENT! Your bank account is locked. Click www.fake-bank.com to verify."],
        ["Hey mom, I will be late for dinner tonight."],
        ["You have won a 1000 dollar Walmart gift card! Text WIN to 8888 now!"]
    ]
)

# Cambiamos debug a True para ver errores futuros en consola si los hay
demo.launch(share=True, debug=True)